backend:
  name: git-gateway
  branch: master #

publish_mode: editorial_workflow
media_folder: "public/uploads"
show_preview_links: false
logo_url: https://www.construtoraconfidence.com/favicon.png

collections:
  - name: "portfolio_items" # Used in routes, e.g., /admin/collections/portfolio_items
    label: "Portifólio" # Used in the UI
    format: json
    folder: "public/_posts/portfolio_items" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.titulo}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      #- {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Título", name: "titulo", widget: "string"}
      - label: "Galeria de imagens"
        name: "photos"
        widget: "list"
        summary: '{{fields.image}}'
        allow_add: true
        fields:
          - label: Imagem
            name: image
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: true
      - {label: "Descrição curta", name: "d_short", widget: "text"}
      - {label: "Descrição completa", name: "d_full", widget: "markdown"}